version: "3"
services:
  web: # Service name will be: 'web'.
    image: milos85vasic/examples:push1 # We will pull the image.
                                       # Replace username/repo:tag with your name and image details.
    deploy:
      replicas: 10 # Run 10 instances of this service
      resources:
        limits:
          cpus: "0.1" # Limit to max 10% of CPU power (across all cores).
          memory: 50M # Limit to 50 MB of ram.
      restart_policy:
        condition: on-failure # Restart containers if one of them fails.
    ports:
      - "80:80" # Map host port 80 to service's port 80.
    networks:
      - webnet
networks:
  webnet: # Define the webnet network with the default settings (which is a load-balanced overlay network).